spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/auth_db?allowPublicKeyRetrieval=true&useSSL=false"
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:mysql}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

security:
  jwt:
    secret: "NDI0MjQyNDI0MjQyNDI0MjQyNDI0MjQyNDI0MjQyNDI0MjQyNDI0MjQyNDI0Mg=="
    expiration-ms: 36000000