server:
  port: 8080

security:
  jwt:
    secret: "NDI0MjQyNDI0MjQyNDI0MjQyNDI0MjQyNDI0MjQyNDI0MjQyNDI0Mg=="

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8990
          predicates:
            - Path=/auth/**

        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/booking/**
          filters:
            - StripPrefix=2

        - id: flight-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/flight/**
          filters:
            - StripPrefix=2
